version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - add_ssh_keys:
          fingerprints:
            - "67:3a:22:2c:f1:74:2c:ae:64:7b:5f:93:69:eb:1e:fb"
       
       # root module, mainly ftp-deploy
       - restore_cache:
          key: dependency-appRootCache-{{ checksum "./package.json" }}
       - run: npm install
       - save_cache:
          key: dependency-appRootCache-{{ checksum "./package.json" }}
          paths:
           - ./node_modules
       
       # client
       - restore_cache:
          key: dependency-appClientCache-{{ checksum "./client/package.json" }}
       - run: npm install --prefix ./client
       - save_cache:
          key: dependency-appClientCache-{{ checksum "./client/package.json" }}
          paths:
           - ./client/node_modules
       - run: npm run build --prefix ./client
       # - run: npm run format --prefix ./client
       # - run: npm run lint --prefix ./client
       # - run: npm test --prefix ./client

       # server
       - restore_cache:
          key: dependency-appServerCache-{{ checksum "./server/package.json" }}
       - run: npm install --prefix ./server
       - save_cache:
          key: dependency-appServerCache-{{ checksum "./server/package.json" }}
          paths:
           - ./server/node_modules
       - run: npm run build --prefix ./server

       # deploy
       - run: cp server/package.json server/build/
       - run: node deploy_server.js
       - run: node deploy_app.js

       # build on server
       - run: git log --oneline --decorate > client/public/changelog.txt
       - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts
       - run: ssh $SSH_USER@$SSH_HOST "cd domains/si.wroblewskipiotr.pl/public_nodejs/ && npm install && devil www restart si.wroblewskipiotr.pl"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master